import type { MemoryItem } from '../src/types.js'

export const seedItems: MemoryItem[] = [
  {
    id: 'coastal-garage',
    title: 'Coastal house with concealed garage',
    description: 'A concrete coastal home where the automatic garage is integrated into the timber façade.',
    kind: 'image',
    image: '/images/coastal-garage.png',
    space: 'Home ideas',
    tags: ['architecture', 'garage', 'concrete', 'timber', 'coastal'],
    palette: ['#273442', '#7b7267', '#b17b43'],
    createdAt: '2026-08-06T08:32:00.000Z',
    favourite: true,
    source: 'Upload',
    aiConfidence: 0.97,
    searchTerms: ['auto parking space', 'automatic garage door', 'car storage', 'modern home facade'],
  },
  {
    id: 'walnut-knife',
    title: 'Walnut-handled santoku',
    description: 'Sculptural Japanese-inspired kitchen knife with brushed steel and a dark faceted handle.',
    kind: 'image',
    image: '/images/walnut-knife.png',
    space: 'Objects',
    tags: ['knife', 'product design', 'japanese', 'walnut', 'steel'],
    palette: ['#e8dfd0', '#827667', '#4b3426'],
    createdAt: '2026-08-05T14:18:00.000Z',
    favourite: false,
    source: 'Upload',
    aiConfidence: 0.99,
    searchTerms: ['design knife', 'chef knife', 'kitchen object', 'minimal product design'],
  },
  {
    id: 'olive-chair',
    title: 'Olive bouclé reading corner',
    description: 'Soft, low lounge chair against pale oak joinery and textured plaster walls.',
    kind: 'image',
    image: '/images/reading-chair.png',
    space: 'Home ideas',
    tags: ['interior', 'chair', 'bouclé', 'reading corner', 'oak'],
    palette: ['#d8cec0', '#6e704e', '#8b735b'],
    createdAt: '2026-08-04T19:42:00.000Z',
    favourite: true,
    source: 'Upload',
    aiConfidence: 0.96,
    searchTerms: ['cozy chair', 'apartment reading nook', 'green lounge seat', 'calm interior'],
  },
  {
    id: 'soft-interfaces',
    title: 'Interfaces that feel like objects',
    description: 'A thoughtful essay about bringing tactility, restraint, and emotional durability to digital tools.',
    kind: 'link',
    url: 'https://www.are.na/',
    domain: 'are.na',
    space: 'Design references',
    tags: ['interface', 'essay', 'tactility', 'digital design'],
    palette: ['#d8c7ed', '#fdede1', '#647567'],
    createdAt: '2026-08-03T11:06:00.000Z',
    favourite: false,
    source: 'Browser',
    aiConfidence: 0.91,
    searchTerms: ['soft ui', 'tactile websites', 'interaction design', 'web inspiration'],
  },
  {
    id: 'slow-travel',
    title: 'A quieter way through Sicily',
    description: 'Small coastal towns, family-run stays, and a train route worth remembering for autumn.',
    kind: 'link',
    url: 'https://www.italia.it/en/sicily',
    domain: 'italia.it',
    space: 'Travel',
    tags: ['sicily', 'slow travel', 'coast', 'autumn'],
    palette: ['#387d8d', '#e1b773', '#f1e4cb'],
    createdAt: '2026-08-01T16:22:00.000Z',
    favourite: false,
    source: 'Browser',
    aiConfidence: 0.94,
    searchTerms: ['italy holiday', 'mediterranean train trip', 'quiet island travel'],
  },
  {
    id: 'book-note',
    title: 'Books on creating a home slowly',
    description: 'Look for writing about homes that become layered over time—not styled all at once.',
    kind: 'note',
    space: 'Reading list',
    tags: ['books', 'home', 'slow living', 'interiors'],
    palette: ['#ef5d48', '#f1ce59', '#faf1df'],
    createdAt: '2026-07-29T09:10:00.000Z',
    favourite: false,
    source: 'Quick note',
    aiConfidence: 0.89,
    searchTerms: ['interior design reading', 'decorating over time', 'home books'],
  },
]
